CG_ROOT_PATH: "data/2024-09-17--19-06-02_nyc_lab_preprocessed"
# FRE: 2024-09-17--19-06-02_fre_apartment_shortscan_preprocessed / 2024-09-23--16-18-51-object_scan_fre_preprocessed
# NYC: 2024-09-17--19-06-02_nyc_lab_preprocessed / "/home/jmmy/research/Datasets/Record3D/2024-10-03--13-20-53-new_large_object_fre_preprocessed"
SCAN_TYPE: "r3d"
USE_YOLO: False
#Fill up empty areas in point cloud for nav planning: 
#mention in array format: [y1:y2, x1:x2].
FILL_UP_GRID_LOCATION: [[69, 71, 67, 72], [69,73, 67, 68], [2, 38, 90, 104]] 
#[[86, 87, 94, 100], [75, 80, 99, 100], [2, 10, 18, 39], [26, 28, 4, 9], [85, 87,  30, 69]]
DILATION_SIZE: 1
OCCUPANCY_SCALE: 10
DISTANCE_THRESHOLD_TO_ADD_POINT: 1.0 # The distance threshold to add waypoints in the navigation waypoints
