WEIGHTS:
  NAV: "weights/torchscript/CUTOUT_WT_True_SD_200_ckpt.99.pvp_combined_net.torchscript"
#WEIGHTS: "weights/CUTOUT_WT_True_SD_200_ckpt.99.pvp.pth"
MAX_EPISODE_STEPS: 150

# Base action params
MAX_LIN_DIST: 0.25  # meters
MAX_ANG_DIST: 15.0  # degrees

SUCCESS_DISTANCE: 0.3
SUCCESS_ANGLE_DIST: 5 # degrees
DISABLE_OBSTACLE_AVOIDANCE: False
USE_OA_FOR_NAV: True
USE_HEAD_CAMERA: True
NAV_ACTION_SPACE_LENGTH: 2

USE_DYNAMIC_YAW: False
DYNAMIC YAW:
  SUCCESS_DISTANCE: 1.10
  SUCCESS_ANGLE_DIST: 20
# General env params
USE_MRCNN: False