defaults:
  - base

# Semantic place
WEIGHTS:
  PLACE: "weights/semantic_place/sp12lhb6v10_12_ckpt.199.torchscript"

# Semantic Place
ACTION_SPACE_LENGTH: 9
JOINT_BLACKLIST: [3]

INITIAL_ARM_JOINT_ANGLE: [0, -180, 180, 0, 0, 90] # The initial orientation of the arm for side grasping (gripper is in object's right hand side)
INITIAL_ARM_JOINT_ANGLES_LEFT_HAND: [0, -180, 180, 0, 0, -90] # The initial orientation of the arm for side grasping (gripper is in object's left hand side)
INITIAL_ARM_JOINT_ANGLES_TOP_DOWN: [-0.91, -92.87, 91.21, 0, 90.01, 0] # The initial orientation of the arm for top down grasping

ARM_JOINT_ANGLES: [0, -125, 80, 0, 85, 0]
ARM_LOWER_LIMITS: [-90, -180, 0, 0, -90, -90]
ARM_UPPER_LIMITS: [90, 0, 180, 0, 90, 90]

# General env params
USE_MRCNN: True